- name: Initiate Datacenter List
  set_fact:
      all_datacenters: []

- name: Add new JSON Objects to List
  set_fact:
        all_datacenters: "{{ all_datacenters +  [[item, datacenters[item].vsphere_cluster, datacenters[item].vsphere_datacenter,  datacenters[item].vsphere_server ]] }}"
  loop: "{{ datacenterList }}"
- debug: msg="{{ item.0 }} {{ item.1 }} {{ item.2 }} {{ item.3}}"
  with_nested:
         - "{{ os_list }}"
         - "{{ all_datacenters }}"
- name: Initiate the builders
  command: "echo {{ item.0 }} {{ item.1 }} {{ item.2 }} {{ item.3}}"
  async: 45
  poll: 0
  with_nested:
    - "{{ os_list }}"
    - "{{ all_datacenters }}"
  register: async_results
- name: Check sync status
  async_status:
    jid: "{{ async_result_item.ansible_job_id }}"
  loop: "{{ async_results.results }}"
  loop_control:
    loop_var: "async_result_item"
  register: async_poll_results
  until: async_poll_results.finished
  retries: 30

  
