---
# tasks file for packer-builder
#Verify that datacenter_tag is either "all" or one of the valid datacenters
- name: Check OS Version 
  assert:
    that:
      - ansible_facts['os_family']|lower == 'Windows'
    fail_msg: "You cannot run this playbook on {{ ansible_facts['os_family'] }}"
    success_msg: "Start Packer builder"
- import_tasks: windows.yml


