
---
  - name: User input
    debug: 
      msg: datacenter tag {{ datacenter_tag }}
  - name: Validate input
    assert :
      that: datacenter_tag != ""
  - name: Create datacenter name(s)
    set_fact:
        datacenterList: "{{ datacenters.keys()|list if datacenter_tag == 'all' else [datacenter_tag] }}"
  - name: List of datacenters
    debug: 
      msg: datacenterList {{ datacenterList }}
  - debug:
       var: item
    loop: "{{ datacenterList }}"
# Copy Files to remove Windows Server
  - name: Copy all contents to remove server
    win_copy:
       src: "{{ role_path }}/files/"
       dest: /tmp
# If datacenter_tag is "all" or "", user datacenterList
  - name: Initiate task builders
    include_tasks: initiate-builder.yml
    when: 
        - datacenterList is defined
        - datacenterList|length > 0

