- hosts: all
  tasks:
    - name: Include vars
      include_vars: vars/perfmon_devtest.yml
      when: (env is defined) and (env|length > 0)
    - name: Include vars
      include_role:
         name: perfmon
      vars:
          perfmon_smtp_host: smtp.sample.gov
          perfmon_email_from: from@sample.gov
          perfmon_email_to: to@sample.gov
